# Generated by Django 4.1.5 on 2023-02-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_reservation_options_alter_whyus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Error phone number', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$')]),
        ),
    ]
