# Generated by Django 4.1.5 on 2023-02-11 16:39

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_reservation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.SmallIntegerField(unique=True)),
                ('photo', models.ImageField(upload_to=main_page.models.Slider.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('h_1', models.CharField(max_length=250)),
                ('desc', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'ordering': ('position',),
            },
        ),
    ]
