# Generated by Django 4.1.5 on 2023-02-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_contactus_alter_slider_desc_alter_slider_h_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('location_text', models.CharField(max_length=50)),
                ('open_hours', models.CharField(max_length=50)),
                ('open_hours_text', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('email_text', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('phone_text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Контактна інформація',
            },
        ),
    ]
