# Generated by Django 4.1.5 on 2023-02-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='desc',
            field=models.TextField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
