# Generated by Django 4.1.5 on 2023-02-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_contactinfo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='h1',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
