# Generated by Django 4.1.5 on 2023-02-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_contactinfo_h1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('google_plus', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Футер',
                'ordering': ('name',),
            },
        ),
    ]
