# Generated by Django 4.1.5 on 2023-02-14 17:13

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Testimonials.get_file_name)),
                ('name', models.CharField(max_length=50)),
                ('prof', models.CharField(max_length=50)),
                ('star', models.SmallIntegerField(blank=True)),
                ('text', models.TextField(max_length=250)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Відгуки',
                'ordering': ('name',),
            },
        ),
    ]
