# Generated by Django 4.1.5 on 2023-02-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='url_video',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
